# Change these first
owner: dat-leth # Your GitHub organization or username, where this repository lives
repo: up.unia.xyz # The name of this repository

sites:
  - name: Homepage
    url: https://www.uni-augsburg.de
  - name: Digicampus
    url: https://digicampus.uni-augsburg.de
  - name: VIBS
    url: https://vibs.uni-augsburg.de/qisserver/pages/cs/sys/portal/hisinoneStartPage.faces
  - name: STUDIS
    url: https://studiswebstud.zv.uni-augsburg.de/FN2SSS/
  - name: Webmail
    url: https://webmail.uni-augsburg.de/
  - name: Kalender
    url: https://mycal.rz.uni-augsburg.de/SOGo/
  - name: Megastore
    url: https://megastore.rz.uni-augsburg.de/fcgi/do
  - name: Mediastore
    url: https://mediastore.rz.uni-augsburg.de/fcgi/do
  - name: WebAuth Login (Digicampus, STUDIS, ...)
    url: https://websso.uni-augsburg.de/login
  - name: SAML Login (Zoom, ...)
    url: https://idp-local.rz.uni-augsburg.de/simplesaml/module.php/core/loginuserpass.php

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: up.unia.xyz
  theme: dark
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: up.unia.xyz
  introTitle: "**up.unia.xyz** zeigt den aktuellen Status und die Uptime verschiedener Web-Services der Universität Augsburg."
  introMessage: Dies ist eine **inoffizielle** Status-Page. Bei Fragen oder Problemen, sendet bitte eine E-Mail an den Service-Desk des Rechenzentrums ([service@rz.uni-augsburg.de](mailto:service@rz.uni-augsburg.de)).
  navbar:
    - title: Status
      href: /
    - title: Rechenzentrum
      href: https://www.uni-augsburg.de/de/organisation/einrichtungen/rz/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
